### ISSUE TITLE
Feature master issue

### ISSUE THREAD

**Issue by haljin** [haljin/paint_schemer#2]
- [x] 404 on GET for a scheme that does not exist
- [ ] List all schemes
- [ ] Delete a scheme
- [ ] More tests
- [x] Fix saving names
- [ ] Scheme view

Long term:
- Authentication
- Ownership of schemes
- Design/styling/etc
